# Generated by Django 4.2 on 2023-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img_big',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_small',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
